name: ThornyaBot
version: '${project.version}'
main: thornyabot.thornyabot.ThornyaBot
api-version: 1.18
authors:
  - "Gusttavo13"
  - "_Vulkano_"
description: Discord Integration JDA
commands: 
  tickets:
    description: "Tickest do Bot"
  verificar:
    description: "Sistema de verificação"
    aliases:
      - "verify"